name: Build NixOS CP ISO

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v30
      with:
        # KHÓA CỨNG BẢN STABLE 25.11 GIỐNG THẦY - CHẤM DỨT LỖI BUS ERROR
        nix_path: nixpkgs=channel:nixos-25.11

    - name: Build ISO
      env:
        NIXPKGS_ALLOW_UNFREE: "1"
      run: |
        nix-build -A config.system.build.isoImage '<nixpkgs/nixos>' -I nixos-config=configuration.nix -o result

    - name: Upload ISO Artifact
      uses: actions/upload-artifact@v4
      with:
        name: nixos-cp-iso
        path: result/iso/*.iso
